service: test-server-ecommers
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  httpApi:
    cors: true

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - "arn:aws:dynamodb:us-west-2:531644786567:*"

functions:
  hello:
    handler: src/hello.hello
    events:
      - httpApi:
          path: /
          method: get

  createProduct:
    handler: src/addProduct.addProduct
    events:
      - httpApi:
          path: /api/products
          method: post

  getProducts:
    handler: src/getProducts.getProducts
    events:
      - httpApi:
          path: /api/products
          method: get

  getProduct:
    handler: src/getProduct.getProduct
    events:
      - httpApi:
          path: /api/products/{id}
          method: get

  # tablas de usuarios
  createUser:
    handler: src/addUser.addUser
    events:
      - httpApi:
          path: /api/users
          method: post

  getUsers:
    handler: src/getUsers.getUsers
    events:
      - httpApi:
          path: /api/users
          method: get

resources:
  Resources:
    productsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: productsTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
